use std::path::Path;

use crate::config::MacK3dConfig;
use crate::error::{Error, Result};
use crate::runtime::exec;
use crate::runtime::kubectl;

const HELM_REPO_NAME: &str = "jenkins";
const HELM_REPO_URL: &str = "https://charts.jenkins.io";
const HELM_CHART: &str = "jenkins/jenkins";

/// Extra plugins beyond the Jenkins chart's default `installPlugins` list.
/// Do **not** list plugins already in chart defaults (e.g. `git`, `workflow-aggregator`) —
/// Helm fails with `[PLUGIN CONFLICT]`.
const ADDITIONAL_PLUGINS: &[&str] = &[
    "lockable-resources",     // CPU_CORES / capacity locks for LoLBench workers
    "plain-credentials",      // Secret text credentials for LLM / forge PATs
    "file-parameters",        // stashedFile: Pipeline-safe upload onto agent workspace
    "copyartifact",           // dispatcher Aggregate stage pulls each shard's trials
    "pipeline-utility-steps", // nodesWithLabel: at least one shard per online worker
    "hidden-parameter",       // ui_profile=user hides developer params, keeping defaults
];

pub async fn install_or_upgrade(helm: &Path, config: &MacK3dConfig) -> Result<()> {
    // Pin Helm to this config's cluster — never use whatever happens to be the current context.
    let kube_context = kubectl::context_name(&config.cluster.name);
    println!("Using Helm kube-context '{kube_context}'…");

    println!("Adding Helm repo '{HELM_REPO_NAME}'…");
    exec::visible(
        helm,
        &[
            "repo",
            "add",
            HELM_REPO_NAME,
            HELM_REPO_URL,
            "--force-update",
        ],
    )
    .await?;

    println!("Updating Helm repo…");
    exec::visible(helm, &["repo", "update", HELM_REPO_NAME]).await?;

    let values = write_helm_values()?;
    println!(
        "Installing Jenkins release '{}' in namespace '{}'…",
        config.jenkins.release_name, config.jenkins.namespace
    );
    println!(
        "Plugins (in addition to chart defaults): {}",
        ADDITIONAL_PLUGINS.join(", ")
    );
    let values_path = values.display().to_string();
    let result = exec::visible(
        helm,
        &[
            "upgrade",
            "--install",
            &config.jenkins.release_name,
            HELM_CHART,
            "--namespace",
            &config.jenkins.namespace,
            "--create-namespace",
            "--kube-context",
            &kube_context,
            "-f",
            &values_path,
            "--wait",
            "--timeout",
            "10m",
        ],
    )
    .await;
    let _ = std::fs::remove_file(&values);
    result
}

fn write_helm_values() -> Result<std::path::PathBuf> {
    let path = std::env::temp_dir().join(format!(
        "mac-k3d-jenkins-values-{}.yaml",
        std::process::id()
    ));
    std::fs::write(&path, helm_values())
        .map_err(|e| Error::Config(format!("failed to write Jenkins Helm values: {e}")))?;
    Ok(path)
}

fn helm_values() -> String {
    let plugins = ADDITIONAL_PLUGINS
        .iter()
        .map(|p| format!("    - {p}"))
        .collect::<Vec<_>>()
        .join("\n");
    let java = crate::prepare::toolchain::java_major();
    format!(
        r#"# Generated by mac-k3d — do not edit by hand.
controller:
  # Workers must run at least this Java (JAVA_MAJOR in pipeline/config/toolchain.env).
  image:
    tagLabel: jdk{java}
  serviceType: LoadBalancer
  installLatestPlugins: true
  # Force plugin list onto existing PVCs / upgrades (otherwise additionalPlugins may never land).
  overwritePlugins: true
  additionalPlugins:
{plugins}
"#
    )
}

pub async fn admin_password(kubectl: &Path, config: &MacK3dConfig) -> Result<String> {
    kubectl::get_secret_decoded(
        kubectl,
        &config.jenkins.namespace,
        &config.jenkins.release_name,
        "jenkins-admin-password",
    )
    .await
}

pub fn ui_url(config: &MacK3dConfig) -> String {
    format!("http://localhost:{}", config.jenkins.host_port)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn helm_values_include_lockable_resources() {
        let path = write_helm_values().unwrap();
        let text = std::fs::read_to_string(&path).unwrap();
        let _ = std::fs::remove_file(&path);
        assert_eq!(text, helm_values());
        assert!(text.contains("lockable-resources"));
        assert!(text.contains("plain-credentials"));
        assert!(text.contains("file-parameters"));
        // Without this, the dispatcher's Aggregate stage fails at runtime.
        assert!(text.contains("copyartifact"));
        // Without this, the dispatcher cannot count online workers.
        assert!(text.contains("pipeline-utility-steps"));
        // Without this, every job's hidden(...) parameter fails to compile.
        assert!(text.contains("hidden-parameter"));
        assert!(!text.contains("- git"));
        assert!(!text.contains("workflow-aggregator"));
        assert!(text.contains("serviceType: LoadBalancer"));
        assert!(text.contains("overwritePlugins: true"));
    }

    #[test]
    fn helm_values_pin_the_controller_java() {
        let text = helm_values();
        let want = format!(
            "controller:\n  # Workers must run at least this Java (JAVA_MAJOR in pipeline/config/toolchain.env).\n  image:\n    tagLabel: jdk{}\n",
            crate::prepare::toolchain::java_major()
        );
        assert!(text.contains(&want), "{text}");
        assert_eq!(text.matches("controller:").count(), 1);
        let values: serde_yaml::Value = serde_yaml::from_str(&text).unwrap();
        assert_eq!(
            values["controller"]["image"]["tagLabel"].as_str(),
            Some(format!("jdk{}", crate::prepare::toolchain::java_major()).as_str())
        );
    }
}
