use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::{Error, Result};
use crate::jenkins_curl::Session;

/// Download Jenkins agent.jar from the controller. Returns whether the jar on
/// disk changed.
///
/// The download goes to a side file first: writing over the jar a running agent
/// JVM has open makes it fail later with `NoClassDefFoundError`.
pub fn download_agent_jar(controller_url: &str, dest: &Path) -> Result<bool> {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Config(format!("failed to create {}: {e}", parent.display())))?;
    }
    let url = format!(
        "{}/jnlpJars/agent.jar",
        controller_url.trim_end_matches('/')
    );
    println!("Downloading agent.jar from {url}");
    let part = dest.with_extension("jar.part");
    let status = Command::new("curl")
        .args(["-fsSL", "-o", &part.display().to_string(), &url])
        .status()
        .map_err(|e| Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: e.into(),
        })?;
    if !status.success() {
        let _ = std::fs::remove_file(&part);
        return Err(Error::CommandFailed {
            cmd: format!("curl {url}"),
            source: anyhow::anyhow!("exit {:?}", status.code()),
        });
    }
    let changed = swap_in_if_different(&part, dest)?;
    if changed {
        println!("Updated {}", dest.display());
    } else {
        println!("agent.jar unchanged");
    }
    Ok(changed)
}

/// Rename `fresh` over `dest` unless the bytes already match. A rename gives
/// the new jar a new inode, so a JVM still reading the old one is unaffected.
fn swap_in_if_different(fresh: &Path, dest: &Path) -> Result<bool> {
    let new = std::fs::read(fresh)
        .map_err(|e| Error::Config(format!("failed to read {}: {e}", fresh.display())))?;
    if std::fs::read(dest).ok().as_deref() == Some(new.as_slice()) {
        let _ = std::fs::remove_file(fresh);
        return Ok(false);
    }
    std::fs::rename(fresh, dest).map_err(|e| {
        Error::Config(format!(
            "failed to move {} to {}: {e}",
            fresh.display(),
            dest.display()
        ))
    })?;
    Ok(true)
}

/// The inbound agent's secret, next to its launch script. agent.jar reads it
/// through `-secret @<file>`, so it is never in the java process's arguments,
/// which every user on the host can read.
pub const SECRET_FILE: &str = ".agent-secret";
const SECRET_PLACEHOLDER: &str = "REPLACE_ME";

pub fn secret_file_for(script_path: &Path) -> PathBuf {
    script_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(SECRET_FILE)
}

/// Write `secret` as the file's one line, mode 0600. Returns whether it changed.
fn write_secret_file(path: &Path, secret: &str) -> Result<bool> {
    let body = format!("{secret}\n");
    let changed = std::fs::read_to_string(path).ok().as_deref() != Some(body.as_str());
    if changed {
        crate::config::write_private(path, body.as_bytes())?;
    } else {
        crate::config::make_private(path)?;
    }
    Ok(changed)
}

/// Write a launch script for the inbound agent (secret filled after registration).
/// Returns whether the script or its secret file changed.
pub fn write_launch_script(
    script_path: &Path,
    controller_url: &str,
    agent_name: &str,
    agent_jar: &Path,
    secret_placeholder: &str,
) -> Result<bool> {
    write_launch_script_with_java(
        script_path,
        controller_url,
        agent_name,
        agent_jar,
        secret_placeholder,
        "java",
    )
}

pub fn write_launch_script_with_java(
    script_path: &Path,
    controller_url: &str,
    agent_name: &str,
    agent_jar: &Path,
    secret: &str,
    java_bin: &str,
) -> Result<bool> {
    if let Some(parent) = script_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Config(format!("failed to create {}: {e}", parent.display())))?;
    }
    let secret_path = secret_file_for(script_path);
    let secret_changed = write_secret_file(&secret_path, secret)?;
    let path = crate::prepare::path_env::agent_tool_path();
    let body = format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
# Generated by mac-k3d. The agent secret is in {secret_file} (mode 600);
# if registration was manual, paste it there.
# LaunchAgents otherwise get PATH=/usr/bin:/bin and miss Docker/Harbor.
export PATH="{path}"
exec "{java}" -jar "{jar}" \
  -url "{url}" \
  -secret "@{secret_file}" \
  -name "{name}" \
  -webSocket
"#,
        secret_file = secret_path.display(),
        path = path,
        java = java_bin,
        jar = agent_jar.display(),
        url = controller_url.trim_end_matches('/'),
        name = agent_name,
    );
    let script_changed =
        std::fs::read_to_string(script_path).ok().as_deref() != Some(body.as_str());
    if script_changed {
        std::fs::write(script_path, body).map_err(|e| {
            Error::Config(format!("failed to write {}: {e}", script_path.display()))
        })?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(script_path, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| Error::Config(e.to_string()))?;
    }
    Ok(script_changed || secret_changed)
}

/// The agent secret in use: the secret file, else the inline `-secret "<hex>"`
/// of a launch script from before the file. None while it is the placeholder.
fn existing_secret(script_path: &Path) -> Option<String> {
    let real = |s: &str| !s.is_empty() && s != SECRET_PLACEHOLDER && !s.starts_with('@');
    if let Ok(text) = std::fs::read_to_string(secret_file_for(script_path)) {
        let line = text.lines().next().unwrap_or("").trim().to_string();
        if real(&line) {
            return Some(line);
        }
    }
    let text = std::fs::read_to_string(script_path).ok()?;
    text.lines()
        .find_map(|l| l.trim().strip_prefix("-secret \""))
        .and_then(|rest| rest.split('"').next())
        .filter(|s| real(s))
        .map(str::to_string)
}

/// Whether the agent can connect: the platform daemons refuse to start without it.
pub fn has_agent_secret(script_path: &Path) -> bool {
    existing_secret(script_path).is_some()
}

/// Register node via Jenkins REST API when token is available.
///
/// Returns Ok(Some(secret)) when registration succeeded, Ok(None) when skipped
/// (no token) or when create succeeded but secret could not be parsed.
pub fn try_register_node(
    controller_url: &str,
    agent_name: &str,
    remote_fs: &Path,
    labels: &[String],
    api_user: Option<&str>,
    api_token: Option<&str>,
) -> Result<Option<String>> {
    let (Some(user), Some(token)) = (api_user, api_token) else {
        println!(
            "\nNo Jenkins API token provided — skipping auto-registration.\n\
             Create a Permanent Agent named '{agent_name}' on the controller, then run the launch script.\n\
             Labels: {}\n\
             Remote root: {}\n\
             Controller: {controller_url}\n",
            labels.join(" "),
            remote_fs.display()
        );
        return Ok(None);
    };

    let base = controller_url.trim_end_matches('/');
    let labels_joined = labels.join(" ");
    let session = Session::open(base, user, token)?;

    // Skip create if node already exists.
    let exists = session.status(&format!("/computer/{agent_name}/api/json")) == Some(200);

    let xml = agent_config_xml(agent_name, remote_fs, &labels_joined);
    if !exists {
        // Modern Jenkins: POST /computer/createItem?name=… with XML body.
        // (doCreateItem expects a Stapler form submission and returns HTTP 400 for raw XML.)
        let create = format!("/computer/createItem?name={}", urlencoding_simple(agent_name));
        println!("Registering Jenkins agent '{agent_name}' on {base} …");
        let reply = session.post_xml(&create, "application/xml", &xml)?;
        if !reply.is(&["200", "201", "302", "303"]) {
            let snippet: String = reply.body.chars().take(240).collect();
            println!(
                "Warning: failed to create agent via API (HTTP {}). {snippet}\n\
                 Create the node in the UI, then paste the secret into {}.",
                reply.code,
                remote_fs.join(SECRET_FILE).display()
            );
            return Ok(None);
        }
    } else {
        // Rewrite an existing node so executors and labels follow this config;
        // the JNLP secret is derived from the node name and survives.
        let path = format!("/computer/{}/config.xml", urlencoding_simple(agent_name));
        match session.post_xml(&path, "application/xml", &xml).map(|r| r.code) {
            Ok(code) if code == "200" || code == "204" => println!(
                "Jenkins agent '{agent_name}' already exists; updated it to {EXECUTORS} executor and labels '{labels_joined}'."
            ),
            Ok(code) => println!(
                "Warning: Jenkins agent '{agent_name}' exists but its config could not be updated (HTTP {code}). \
                 Set # of executors to {EXECUTORS} on {base}/computer/{agent_name}/configure."
            ),
            Err(err) => println!("Warning: could not update agent '{agent_name}' ({err})."),
        }
    }

    let secret = session
        .get(&format!("/computer/{agent_name}/slave-agent.jnlp"))
        .and_then(|text| parse_jnlp_secret(&text));

    match secret {
        Some(secret) => {
            println!("Retrieved agent connection secret.");
            Ok(Some(secret))
        }
        None => {
            println!(
                "Agent created (or already present), but could not parse JNLP secret.\n\
                 Open {base}/computer/{agent_name}/ and copy the secret into {}.",
                remote_fs.join(SECRET_FILE).display()
            );
            Ok(None)
        }
    }
}

/// One eval build per worker. Each build locks every core of its worker and
/// Harbor fills them, so the queue hands the next shard to whichever worker
/// frees up first instead of piling shards onto one node.
const EXECUTORS: u32 = 1;

fn agent_config_xml(name: &str, remote_fs: &Path, labels: &str) -> String {
    let executors = EXECUTORS;
    format!(
        r#"<?xml version='1.1' encoding='UTF-8'?>
<slave>
  <name>{name}</name>
  <description>mac-k3d worker agent</description>
  <remoteFS>{remote}</remoteFS>
  <numExecutors>{executors}</numExecutors>
  <mode>NORMAL</mode>
  <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
  <launcher class="hudson.slaves.JNLPLauncher">
    <workDirSettings>
      <disabled>false</disabled>
      <internalDir>remoting</internalDir>
      <failIfWorkDirIsMissing>false</failIfWorkDirIsMissing>
    </workDirSettings>
    <webSocket>true</webSocket>
  </launcher>
  <label>{labels}</label>
  <nodeProperties/>
</slave>
"#,
        remote = remote_fs.display(),
    )
}

/// Parse inbound-agent secret from slave-agent.jnlp XML.
pub fn parse_jnlp_secret(text: &str) -> Option<String> {
    // Modern: <argument>SECRET</argument><argument>NAME</argument>…
    if let Some(idx) = text.find("<argument>") {
        let rest = &text[idx + "<argument>".len()..];
        let end = rest.find("</argument>")?;
        let first = rest[..end].trim();
        if !first.is_empty() && !first.starts_with('-') {
            return Some(first.to_string());
        }
    }
    // Legacy: <secret>HEX</secret>
    if let Some(idx) = text.find("<secret>") {
        let rest = &text[idx + "<secret>".len()..];
        let end = rest.find("</secret>")?;
        return Some(rest[..end].trim().to_string());
    }
    // Legacy: <argument>-secret</argument><argument>HEX</argument>
    if let Some(idx) = text.find("-secret</argument>") {
        let after = &text[idx + "-secret</argument>".len()..];
        let start = after.find("<argument>")? + "<argument>".len();
        let end = after[start..].find("</argument>")? + start;
        return Some(after[start..end].trim().to_string());
    }
    None
}

fn urlencoding_simple(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_' | '.' | '~' => c.to_string(),
            _ => format!("%{:02X}", c as u8),
        })
        .collect()
}

pub fn default_agent_name() -> String {
    let host = Command::new("hostname")
        .arg("-s")
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "mac".into());
    format!("mac-{host}")
}

pub fn default_remote_fs() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join("jenkins-agent")
}

/// The Java the launch script runs: the recorded one when it runs, else what
/// discovery picks (a Java that meets JAVA_MAJOR first), else `java` on PATH.
pub fn agent_java(config: &crate::config::MacK3dConfig) -> String {
    config
        .dependencies
        .java
        .binary
        .as_ref()
        .filter(|p| p.exists())
        .map(|p| p.display().to_string())
        .filter(|s| {
            std::process::Command::new(s)
                .arg("-version")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        })
        .or_else(|| {
            crate::prepare::discovery::best_java().map(|(bin, _)| bin.display().to_string())
        })
        .unwrap_or_else(|| "java".into())
}

/// Download jar, register node (if credentials present), write launch script.
pub fn ensure_worker_agent(config: &crate::config::MacK3dConfig) -> Result<()> {
    use crate::config::NodeRole;
    use crate::prepare::resources;

    if !matches!(config.role, NodeRole::Worker) {
        return Ok(());
    }
    let Some(url) = config.jenkins_agent.controller_url.clone() else {
        return Ok(());
    };
    let name = config
        .jenkins_agent
        .name
        .clone()
        .unwrap_or_else(default_agent_name);
    let jar = config.jenkins_agent.agent_jar.clone().unwrap_or_else(|| {
        config
            .storage
            .downloads_dir()
            .unwrap_or_else(|| PathBuf::from("downloads"))
            .join("jenkins-agent")
            .join("agent.jar")
    });
    let remote_fs = config
        .jenkins_agent
        .remote_fs
        .clone()
        .unwrap_or_else(default_remote_fs);

    // Controller may not be up yet during first prepare — do not abort the whole wizard.
    let mut jar_changed = false;
    let jar_ok = match download_agent_jar(&url, &jar) {
        Ok(changed) => {
            jar_changed = changed;
            true
        }
        Err(e) => {
            println!(
                "Note: could not download agent.jar from {url} ({e}).\n\
                 Jenkins controller is probably not running yet.\n\
                 Config will still be saved. After `mac-k3d start` / Jenkins is up, run:\n\
                   mac-k3d config -c <this-worker-config>"
            );
            false
        }
    };

    let secret = if jar_ok {
        try_register_node(
            &url,
            &name,
            &remote_fs,
            &config.jenkins_agent.labels,
            config.jenkins_agent.api_user(),
            config.jenkins_agent.api_token(),
        )?
    } else {
        None
    };
    let script = remote_fs.join("launch-agent.sh");
    // Without API credentials there is no new secret; keep the one already in use.
    let secret = secret
        .or_else(|| existing_secret(&script))
        .unwrap_or_else(|| SECRET_PLACEHOLDER.into());

    let java_bin = agent_java(config);

    let script_changed =
        write_launch_script_with_java(&script, &url, &name, &jar, &secret, &java_bin)?;
    if script_changed {
        println!(
            "Wrote agent launch script: {} (java: {java_bin})",
            script.display()
        );
    } else {
        println!("Agent launch script unchanged: {}", script.display());
    }

    if jar_ok {
        resources::register_agent_cpu_cores(
            &url,
            &name,
            &config.resources.cpu_cores_label,
            config.jenkins_agent.cpu_cores,
            config.jenkins_agent.api_user(),
            config.jenkins_agent.api_token(),
        )?;
        crate::prepare::agent_service::install_and_start(
            &script,
            &remote_fs,
            jar_changed || script_changed,
        )?;
    } else {
        println!("Skipped agent daemon start until agent.jar is available from the controller.");
    }

    Ok(())
}

/// Stop LaunchAgent, then remove Jenkins node + CPU_CORES lockable resources.
pub fn remove_worker_agent(config: &crate::config::MacK3dConfig) -> Result<()> {
    use crate::config::NodeRole;
    use crate::prepare::resources;

    if !matches!(config.role, NodeRole::Worker) {
        return Ok(());
    }

    // Always stop local agent process first.
    let _ = crate::prepare::agent_service::stop_and_uninstall();

    let Some(url) = config.jenkins_agent.controller_url.as_deref() else {
        return Ok(());
    };
    let name = config
        .jenkins_agent
        .name
        .clone()
        .unwrap_or_else(default_agent_name);

    let user = config.jenkins_agent.api_user();
    let token = config.jenkins_agent.api_token();

    delete_node(url, &name, user, token)?;
    resources::remove_agent_cpu_cores(
        url,
        &name,
        &config.resources.cpu_cores_label,
        config.jenkins_agent.cpu_cores,
        user,
        token,
    )?;
    Ok(())
}

/// Stop only the local LaunchAgent (leave Jenkins node registered).
pub fn stop_worker_agent_process() -> Result<()> {
    crate::prepare::agent_service::stop_and_uninstall()
}

/// Delete a permanent agent via `POST /computer/{name}/doDelete`.
pub fn delete_node(
    controller_url: &str,
    agent_name: &str,
    api_user: Option<&str>,
    api_token: Option<&str>,
) -> Result<()> {
    let (Some(user), Some(token)) = (api_user, api_token) else {
        println!(
            "No Jenkins API token — skipping node delete for '{agent_name}'.\n\
             Remove it manually under Manage Jenkins → Nodes on {controller_url}."
        );
        return Ok(());
    };

    let base = controller_url.trim_end_matches('/');
    let session = Session::open(base, user, token)?;
    let exists = session.status(&format!("/computer/{agent_name}/api/json")) == Some(200);
    if !exists {
        println!("Jenkins agent '{agent_name}' not present on {base}; nothing to delete.");
        return Ok(());
    }

    println!("Deleting Jenkins agent '{agent_name}' on {base} …");
    let reply = session.post(&format!("/computer/{agent_name}/doDelete"))?;
    if reply.is(&["200", "302", "303"]) {
        println!("Deleted Jenkins agent '{agent_name}'.");
    } else {
        println!(
            "Warning: failed to delete agent '{agent_name}' (HTTP {}). Remove it in the Jenkins UI if it remains.",
            reply.code
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_restart_only_when_jar_or_script_changed() {
        use crate::platform::{agent_action, AgentAction};

        let tmp = tempfile::tempdir().unwrap();
        let jar = tmp.path().join("agent.jar");
        let part = tmp.path().join("agent.jar.part");
        std::fs::write(&part, b"remoting-3386").unwrap();
        assert!(swap_in_if_different(&part, &jar).unwrap(), "first download installs the jar");
        std::fs::write(&part, b"remoting-3386").unwrap();
        assert!(!swap_in_if_different(&part, &jar).unwrap(), "same bytes leave it alone");
        assert!(!part.exists());
        std::fs::write(&part, b"remoting-3401").unwrap();
        assert!(swap_in_if_different(&part, &jar).unwrap());
        assert_eq!(std::fs::read(&jar).unwrap(), b"remoting-3401");

        let script = tmp.path().join("launch-agent.sh");
        let write = |name: &str| {
            write_launch_script_with_java(&script, "http://c:8080", name, &jar, "s3cr3t", "java")
                .unwrap()
        };
        assert!(write("node-a"));
        assert!(!write("node-a"));
        assert!(write("node-b"));

        assert_eq!(agent_action(true, false), AgentAction::LeaveRunning);
        assert_eq!(agent_action(true, true), AgentAction::Restart);
        assert_eq!(agent_action(false, false), AgentAction::Start);
        assert_eq!(agent_action(false, true), AgentAction::Start);
    }

    #[test]
    fn parse_modern_jnlp_secret() {
        let xml = r#"<jnlp><application-desc><argument>abc123secret</argument><argument>mac-host</argument><argument>-webSocket</argument></application-desc></jnlp>"#;
        assert_eq!(parse_jnlp_secret(xml).as_deref(), Some("abc123secret"));
    }

    #[test]
    fn agent_registers_with_one_executor() {
        let xml = agent_config_xml("mac-host", Path::new("/tmp/agent"), "lolbench mac-host");
        assert!(xml.contains("<numExecutors>1</numExecutors>"));
        assert!(xml.contains("<label>lolbench mac-host</label>"));
        assert!(xml.contains("<remoteFS>/tmp/agent</remoteFS>"));
    }

    #[test]
    fn config_without_api_token_keeps_the_agent_secret() {
        let tmp = tempfile::tempdir().unwrap();
        let script = tmp.path().join("launch-agent.sh");
        let jar = tmp.path().join("agent.jar");
        assert_eq!(existing_secret(&script), None);
        write_launch_script_with_java(&script, "http://c:8080", "n", &jar, "REPLACE_ME", "java")
            .unwrap();
        assert_eq!(existing_secret(&script), None);
        write_launch_script_with_java(&script, "http://c:8080", "n", &jar, "s3cr3t", "java")
            .unwrap();
        assert_eq!(existing_secret(&script).as_deref(), Some("s3cr3t"));
    }

    fn mode(path: &Path) -> u32 {
        use std::os::unix::fs::PermissionsExt;
        std::fs::metadata(path).unwrap().permissions().mode() & 0o777
    }

    #[test]
    fn the_secret_lives_in_a_private_file_not_the_launch_script() {
        let tmp = tempfile::tempdir().unwrap();
        let script = tmp.path().join("launch-agent.sh");
        let jar = tmp.path().join("agent.jar");
        let secret = "0123abcd0123abcd";
        assert!(
            write_launch_script_with_java(&script, "http://c:8080", "n", &jar, secret, "java")
                .unwrap()
        );
        let body = std::fs::read_to_string(&script).unwrap();
        let file = tmp.path().join(SECRET_FILE);
        assert!(!body.contains(secret), "{body}");
        assert!(
            body.contains(&format!("-secret \"@{}\"", file.display())),
            "{body}"
        );
        assert_eq!(std::fs::read_to_string(&file).unwrap(), format!("{secret}\n"));
        assert_eq!(mode(&script), 0o700);
        assert_eq!(mode(&file), 0o600);
        assert!(has_agent_secret(&script));

        // A new secret alone restarts the agent; a wider mode is tightened on the next run.
        assert!(
            write_launch_script_with_java(&script, "http://c:8080", "n", &jar, "ffff0000", "java")
                .unwrap()
        );
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&file, std::fs::Permissions::from_mode(0o644)).unwrap();
        }
        assert!(
            !write_launch_script_with_java(&script, "http://c:8080", "n", &jar, "ffff0000", "java")
                .unwrap()
        );
        assert_eq!(mode(&file), 0o600);
    }

    #[test]
    fn an_inline_secret_from_an_old_script_moves_to_the_file() {
        let tmp = tempfile::tempdir().unwrap();
        let script = tmp.path().join("launch-agent.sh");
        let jar = tmp.path().join("agent.jar");
        std::fs::write(
            &script,
            "#!/usr/bin/env bash\nexec \"java\" -jar \"agent.jar\" \\\n  -url \"http://c:8080\" \\\n  -secret \"oldhex42\" \\\n  -name \"n\" \\\n  -webSocket\n",
        )
        .unwrap();
        assert_eq!(existing_secret(&script).as_deref(), Some("oldhex42"));
        let kept = existing_secret(&script).unwrap();
        assert!(
            write_launch_script_with_java(&script, "http://c:8080", "n", &jar, &kept, "java")
                .unwrap()
        );
        assert!(!std::fs::read_to_string(&script).unwrap().contains("oldhex42"));
        assert_eq!(existing_secret(&script).as_deref(), Some("oldhex42"));
    }

    #[test]
    fn the_daemon_guard_reads_the_secret_file() {
        let tmp = tempfile::tempdir().unwrap();
        let script = tmp.path().join("launch-agent.sh");
        let jar = tmp.path().join("agent.jar");
        assert!(!has_agent_secret(&script));
        write_launch_script_with_java(&script, "http://c:8080", "n", &jar, SECRET_PLACEHOLDER, "java")
            .unwrap();
        assert!(!has_agent_secret(&script), "the placeholder is not a secret");
        std::fs::write(tmp.path().join(SECRET_FILE), "pasted0123\n").unwrap();
        assert!(has_agent_secret(&script), "a secret pasted into the file is picked up");
    }

    #[test]
    fn parse_legacy_secret_tag() {
        let xml = r#"<jnlp><secret>deadbeef</secret></jnlp>"#;
        assert_eq!(parse_jnlp_secret(xml).as_deref(), Some("deadbeef"));
    }
}
